import { offers, formatPrice } from "./inquiry";

export const sellerName = "PT Waskita Cakrawarti Digital";
export const policyDate = "3 Oktober 2026";
export const taxNotice = "Pajak yang berlaku akan dihitung dan ditampilkan sesuai status perpajakan penjual dan ketentuan yang berlaku.";
export const legalPages = [
  { slug: "ownership", title: "Identitas & kepemilikan", description: "Identitas operator Ranel, bentuk badan usaha, kepemilikan materi dan batas verifikasi informasi legal.", sections: [
    { title: "Brand dan operator", text: ["Ranel adalah brand yang dioperasikan oleh PT Waskita Cakrawarti Digital, Perseroan Perorangan. Identitas ini bersumber dari informasi dan referensi legal yang dikendalikan founder; bukan hasil autentikasi registrasi independen oleh pelaksana website.", "Domisili referensi operator: Kabupaten Banyumas, Jawa Tengah, Indonesia. Nomor registrasi AHU tidak dipublikasikan sampai rekonsiliasi dokumen dan keputusan publikasinya selesai. NIB, NPWP, KBLI, status perpajakan dan izin PMSE tidak dinyatakan terverifikasi di halaman ini."] },
    { title: "Hak atas informasi dan materi", text: ["Pembeli tetap memiliki hak atas informasi usahanya sendiri. Template, brand dan metodologi reusable Ranel tetap milik Ranel kecuali kesepakatan tertulis lain. Penggunaan materi mengikuti Lisensi Produk; keberadaan badan usaha bukan klaim merek dagang terdaftar."] },
    { title: "Referensi resmi", text: ["Referensi AHU dan OSS tersedia pada hub legal untuk informasi umum. Tautan bukan sertifikasi kepatuhan atau bukti izin tertentu untuk setiap kegiatan Ranel."] },
  ] },
  { slug: "terms", title: "Ketentuan produk & penggunaan", description: "Ketentuan paket dokumen Ranel: scope, harga sekali bayar, penyiapan manual, dukungan, lisensi dan penanganan keluhan.", sections: [
    { title: "Model dan cakupan", text: ["Ranel menyediakan paket dokumen praktis Starter, Growth dan System untuk operator barber berbahasa Indonesia. System mencakup dokumen pemetaan operating system, bukan aplikasi atau subscription. Growth mencakup Starter; System mencakup Growth. Tidak harus membeli paket lebih rendah terlebih dahulu.", "Tidak termasuk software custom, POS/CRM/booking, hosting, integrasi, pengiriman pesan otomatis, legal drafting bespoke, unlimited consulting/revisions atau jaminan hasil bisnis."] },
    { title: "Harga dan kesepakatan", text: ["Harga dasar sekali bayar IDR: Starter Rp39.000, Growth Rp79.000, System Rp149.000. Rujuk Pricing & Payment untuk promo, fee dan pajak. Penjualan online dan pembayaran belum dibuka. Inquiry atau membuka WhatsApp bukan order, invoice maupun persetujuan pembayaran.", "Sebelum transaksi nantinya, paket/version, input, batas tailoring, jumlah yang dibayar, cara/waktu delivery dan dukungan harus jelas dan disepakati. Jumlah final ditampilkan sebelum pembayaran ketika checkout sudah live. Jangan mengirim pembayaran berdasarkan halaman informasi ini."] },
    { title: "Input, penyiapan dan delivery", text: ["Input minimum: nama usaha, layanan/menu, harga usaha dari pembeli, hari/jam operasi, kanal kontak dan logo opsional. Field tambahan Growth/System hanya yang dibutuhkan. Jangan kirim password, payment credentials, informasi identitas yang tidak perlu atau database pelanggan.", "Materi standard reusable dapat disesuaikan terbatas pada input tersebut dan wording sederhana. Bundle versioned diperiksa sebelum delivery melalui kanal manual yang disepakati. Pembayaran harus terkonfirmasi melalui proses berwenang sebelum fulfillment sesuai kesepakatan; tidak ada instant download atau SLA penyiapan yang dijanjikan oleh website."] },
    { title: "Penerimaan, dukungan dan revisi", text: ["Penerimaan mencakup bundle diterima, file dapat dibuka, cocok dengan manifest dan core workflow dapat digunakan. Bukan jaminan pertumbuhan, revenue, profit atau retensi. Support/revisi terbatas pada scope yang disepakati; permintaan baru dibahas sebagai perubahan cakupan, bukan manfaat unlimited.", "File hilang, rusak/tidak bisa diakses atau tidak sesuai scope dapat dilaporkan privat untuk pemeriksaan/remedy. Dukungan utama 1:1 WhatsApp; tidak ada email resmi atau response-day promise yang dipublikasikan sebelum benar-benar siap."] },
    { title: "Hak, cancellation dan complaints", text: ["Materi hanya untuk usaha pembeli sendiri; lihat Lisensi Produk. Pembatalan/perubahan, refund dan remedy mengikuti halaman kebijakan terkait dan hak wajib yang berlaku. Tidak ada blanket no-refund rule. Keluhan ditangani privat melalui kanal kontak dan diekskalasi kepada pengelola."] },
    { title: "Versi dan perubahan", text: ["Versi sumber awal 1.0. Scope/version dan ketentuan yang disepakati dicatat sebelum transaksi; perubahan berikutnya tidak diam-diam mengganti kesepakatan order lama. Update/revisi tidak berarti hak layanan atau pembaruan tanpa batas. Ketentuan applicability legal/tax dan readiness fulfillment masih menjadi gate sebelum live commerce."] },
  ] },
  { slug: "pricing-payment", title: "Harga & pembayaran", description: "Harga dasar paket Ranel dalam IDR, sekali bayar, promo terkendali, biaya transparan dan status pembayaran belum aktif.", sections: [
    { title: "Harga dasar, bukan langganan", text: ["Starter Rp39.000 • Growth Rp79.000 • System Rp149.000. Seluruh paket sekali bayar, IDR, bounded/manual selama pilot. Tidak ada recurring fee, default discount atau keharusan upgrade berurutan."] },
    { title: "Promo terkendali", text: ["Diskon hanya melalui kode promo dengan batas maksimum 40% dari harga dasar. Satu kode per order, tidak stacking, periode berlaku dan produk eligible harus eksplisit; redemption cap bila ditetapkan harus jelas. Tidak ada kode promo atau redemption engine aktif sekarang. Harga dasar tetap referensi komersial, bukan diskon permanen tersembunyi."] },
    { title: "Fee, pajak dan payable", text: ["Prinsip default: tidak ada payment surcharge tersembunyi. Biaya provider diperhitungkan internal kecuali ada aturan komersial baru yang disetujui dan diinformasikan sebelumnya.", taxNotice, "Status perpajakan penjual, klasifikasi transaksi serta tax-inclusive/tax-exclusive belum divalidasi. Tidak ada tarif universal atau nominal pajak ditetapkan pada website. Jumlah final yang harus dibayar akan ditampilkan sebelum pembayaran ketika checkout live."] },
    { title: "Payment belum aktif", text: ["Harga yang ditampilkan bukan izin menerima pembayaran atau bukti checkout tersedia. Jangan mengirim dana melalui kanal yang belum dikonfirmasi. Duitku adalah provider yang direncanakan; integrasi merchant, confirmation, persistence dan transaksi live belum diverifikasi."] },
  ] },
  { slug: "refund-policy", title: "Pembatalan, refund & remedy", description: "Cara meminta pembatalan, koreksi file atau refund Ranel secara privat, dengan pemeriksaan scope dan hak konsumen yang tetap dijaga.", sections: [
    { title: "Cara meminta bantuan", text: ["Gunakan kanal 1:1 WhatsApp melalui Kontak. Jelaskan paket, masalah dan solusi yang diharapkan; sertakan referensi order/kesepakatan bila sudah ada. Website saat ini belum membuat order/payment. Jangan kirim password, data bank lengkap, identity documents atau informasi pelanggan barber. Jangan membahas transaksi privat di grup community."] },
    { title: "Masalah yang diperiksa", text: ["Non-delivery; file hilang, rusak atau tidak dapat diakses; ketidaksesuaian material terhadap scope; duplicate/incorrect payment bila transaksi kelak sudah tersedia; permintaan cancellation/change; serta keadaan lain yang diatur kesepakatan dan hukum yang berlaku.", "Pengelola memeriksa kesepakatan, tahap penyiapan/delivery, bukti yang relevan dan payment confirmation. Remedy yang sesuai dapat berupa perbaikan, penggantian akses/file, penyerahan item yang kurang, penyesuaian atau refund sesuai hasil pemeriksaan. Tidak semua kasus otomatis full refund; tidak ada larangan refund mutlak."] },
    { title: "Tahap pembatalan dan perubahan", text: ["Sebelum ada kesepakatan/payment, sampaikan bila diskusi tidak dilanjutkan. Setelah kesepakatan, sebelum/selama penyiapan atau setelah delivery, permintaan dinilai terhadap pekerjaan dan materi yang telah diterima, kesepakatan serta hak wajib yang berlaku. Tidak menetapkan penalty, cutoff hari atau aturan no-refund after download baru tanpa dasar."] },
    { title: "Keputusan, catatan dan escalation", text: ["Request, pemeriksaan, keputusan dan pelaksanaan harus dibedakan; bila transaksi ada, hubungkan dengan order/payment, alasan, amount, tanggal dan pihak berwenang. Tidak ada refund executor/provider refund API aktif. Pengelola menjelaskan hasil dan langkah selanjutnya secara privat; waktu penanganan ditentukan sesuai kesepakatan dan kewajiban yang berlaku, bukan angka hari yang belum disetujui.", "Hak konsumen yang wajib menurut ketentuan berlaku tetap dipertahankan. Halaman ini bukan sertifikasi legal compliance. Permintaan yang belum selesai dapat diekskalasi melalui jalur complaints kepada pengelola."] },
  ] },
  { slug: "privacy", title: "Privasi & data pribadi", description: "Cara Ranel menangani website, inquiry privat dan input minimal penyiapan kit, tanpa akun, order database atau pembayaran aktif.", sections: [
    { title: "Website saat ini", text: ["Tidak ada akun, database inquiry, order database, pembayaran aktif, form penyimpanan atau analytics tambahan pada aplikasi PUBLIC. Rancangan pesan tidak dikirim atau disimpan website. Cloudflare dapat memproses informasi teknis seperti IP/request untuk hosting dan keamanan; aplikasi tidak menambahkan cookies/tracking/local storage."] },
    { title: "Inquiry dan dukungan privat", text: ["Tautan inquiry membuka WhatsApp; pesan hanya dikirim ketika Anda sendiri mengirimnya. Pemrosesan oleh WhatsApp mengikuti kebijakan layanan tersebut. Pengelola dapat menangani percakapan secara manual untuk menjawab inquiry/support, bukan mengimpor customer databases atau mengirim campaign otomatis.", "Input yang relevan kelak terbatas pada nama usaha, menu/harga, hari/jam, kanal kontak, logo opsional dan field workflow yang diperlukan. Jangan kirim password, payment credentials, NIK/NPWP pribadi atau daftar pelanggan. Jangan membagikan order/refund/data usaha privat di community."] },
    { title: "Tujuan, dasar dan pihak ketiga", text: ["Informasi dibatasi untuk komunikasi yang diminta, penyiapan/delivery yang disepakati, dukungan, keluhan dan kewajiban yang berlaku. Sebelum pengumpulan order/customer data baru, jelaskan tujuan, dasar yang sesuai seperti perjanjian/izin/kewajiban yang berlaku, provider yang digunakan dan aksesnya. Jangan menganggap semua tujuan sebagai izin marketing.", "Cloudflare dan WhatsApp adalah layanan yang digunakan saat ini. Duitku direncanakan, tetapi payment processing belum aktif. Tidak mengklaim customer data sudah dikirim ke Duitku. Perubahan pemrosesan membutuhkan pembaruan policy sebelum aktif."] },
    { title: "Retensi, permintaan dan keamanan", text: ["Periode retensi/penghapusan operasional pesan belum ditetapkan sebagai angka tetap; informasi tidak boleh dikumpulkan melebihi kebutuhan. Sebelum live commerce, jadwal retention, kewajiban record, access control dan penghapusan perlu ditetapkan. Kebijakan ini tidak mengklaim prosedur otomatis yang belum dibangun.", "Untuk menanyakan akses, koreksi, penghentian komunikasi atau penghapusan informasi Anda, hubungi pengelola melalui kanal privat pada Kontak. Verifikasi permintaan seperlunya tanpa meminta identitas berlebihan; kewajiban pencatatan/hak yang berlaku dapat mempengaruhi penyelesaian. Tidak ada customer portal atau email resmi yang dikarang."] },
  ] },
  { slug: "license", title: "Lisensi produk", description: "Hak penggunaan materi Ranel untuk usaha pembeli, batas redistribusi dan kepemilikan informasi yang disediakan pembeli.", sections: [
    { title: "Penggunaan usaha sendiri", text: ["Pembeli boleh memakai dan menyesuaikan materi yang dibeli untuk usahanya sendiri. Tidak boleh menjual ulang, mensublisensikan, mendistribusikan publik atau mengemas ulang template Ranel sebagai produk sendiri. Tidak ada klaim subscription atau software access."] },
    { title: "Kepemilikan informasi dan reusable IP", text: ["Pembeli tetap memiliki hak atas informasi usaha yang disediakannya. Template reusable, brand dan metodologi reusable Ranel tetap milik Ranel kecuali kesepakatan tertulis lain. Tidak mengklaim registrasi merek dagang dari keberadaan badan usaha."] },
    { title: "Versioning, revisions dan pertanyaan", text: ["Versi awal 1.0. Update/revisi mengikuti scope produk/kesepakatan yang dipublikasikan; tidak berarti perpetual updates, unlimited revisions atau konsultasi tanpa batas. Untuk penggunaan di luar scope, lisensi/IP atau kendala file, hubungi Ranel privat terlebih dahulu. Hak wajib yang berlaku tidak dihapus oleh halaman ini."] },
  ] },
  { slug: "complaints", title: "Keluhan & dukungan", description: "Kanal privat Ranel untuk pertanyaan produk, dukungan file, keluhan dan koordinasi remedy, tanpa email atau response SLA palsu.", sections: [
    { title: "Kanal utama 1:1 WhatsApp", text: ["Mulai dari Kontak untuk diskusi/support privat. Sebutkan paket dan kendala; bila ada order, gunakan referensi yang relevan dan bukti minimal. Website tidak mengirim pesan atau mengakui tiket otomatis. Hindari membagikan nomor bank lengkap, credentials, dokumen identitas atau data customer barber."] },
    { title: "Proses dan escalation", text: ["Pengelola meninjau request, mengonfirmasi masalah/scope, menjelaskan langkah lanjut, lalu mencatat hasil sesuai kebutuhan. Isu refund/payment/scope dapat diekskalasi kepada pengelola berwenang. Tidak ada janji response-day yang belum disetujui; dukungan/revisi bounded, bukan unlimited consulting. Lihat kebijakan refund/remedy untuk kasus delivery/file/payment."] },
    { title: "Email resmi dan community", text: ["Email resmi sebagai kanal formal belum dikonfigurasi/dikonfirmasi untuk publik; tidak ada alamat email yang dipublikasikan saat ini. Gunakan kontak privat existing untuk memulai dan minta penjelasan penanganan informasi bila perlu.", "WhatsApp Community/Group adalah opsi masa depan untuk edukasi, tips dan update, bukan kanal order/payment/refund atau data usaha privat. Tidak ada community/support channel baru yang dinyatakan aktif. Kontak regulator wajib yang relevan perlu diperiksa sesuai peran usaha sebelum live commerce."] },
  ] },
  { slug: "payment-provider", title: "Rencana payment provider", description: "Duitku adalah provider pembayaran yang direncanakan untuk Ranel; production checkout dan transaksi belum diaktifkan.", sections: [
    { title: "Duitku masih rencana integrasi", text: ["Ranel berencana menggunakan Duitku dengan target production/live. Engineering adapter ada, tetapi merchant contract, credentials, persistence dan end-to-end transaksi belum terverifikasi sebagai sistem Ranel yang aktif. Tidak ada checkout atau payment-method logo aktif pada website ini."] },
    { title: "Batas authority", text: ["Browser return atau event JavaScript bukan bukti pembayaran. Status finansial nantinya harus ditetapkan oleh verifikasi server/provider dan record durable. Halaman ini tidak memberi instruksi transfer, membuat invoice, menampilkan merchant ID atau mengungkap credential."] },
    { title: "Informasi provider", text: ["Informasi umum Duitku dapat dibaca dari situs resminya. Tautan referensi bukan endorsement/certification atau bukti channel pembayaran Ranel sudah live."] },
  ] },
] as const;
export const legalPaths = ["/legal", ...legalPages.map(p => `/legal/${p.slug}`)];
export function LegalIdentity() {
  return <aside class="legal-identity" aria-label="Identitas operator">
    <p class="eyebrow">Ranel / Identitas operator</p>
    <p><strong>Dioperasikan oleh {sellerName}</strong><br />Perseroan Perorangan</p>
    <p class="small">Referensi identitas founder; bukan verifikasi legal independen. Registrasi/izin dan tax applicability tetap membutuhkan validasi sebelum live commerce.</p>
  </aside>;
}
export function LegalContent({ slug }: { slug?: string }) {
  const page = legalPages.find(p => p.slug === slug);
  return <article class="section legal-content" id="legal-policy">
    <p class="eyebrow">Legal &amp; Policies / Informasi pilot</p>
    <h1>{page ? page.title : "Legal & Policies"}</h1>
    <p class="policy-dates">Versi informasi 1.0 · Berlaku untuk informasi website: {policyDate} · Diperbarui: {policyDate}</p>
    <LegalIdentity />
    <p class="legal-status">Penjualan online dan pembayaran belum dibuka. Informasi ini bukan klaim sertifikasi kepatuhan; final legal/tax applicability dan fulfillment masih menjadi gate sebelum live commerce.</p>
    {page ? page.sections.map(section => <section key={section.title}><h2>{section.title}</h2>{section.text.map(text => <p key={text}>{text}</p>)}</section>) : <>
      <p>Kenali operator, cakupan produk, harga, hak penggunaan, data dan jalur dukungan sebelum membahas pilot.</p>
      <nav class="legal-grid" aria-label="Dokumen kebijakan">{legalPages.map(p => <a class="legal-card" href={`/legal/${p.slug}`} key={p.slug}><h2>{p.title}</h2><p>{p.description}</p><span class="small">Versi 1.0 · {policyDate}</span></a>)}</nav>
      <section><h2>Referensi resmi</h2><ul><li><a href="https://ahu.go.id/">Ditjen AHU</a></li><li><a href="https://oss.go.id/">OSS</a></li><li><a href="https://jdih.kemendag.go.id/">JDIH Kementerian Perdagangan</a></li><li><a href="https://jdih.komdigi.go.id/produk_hukum/view/id/832/t/undangundang%20nomor%2027%20tahun%202022">UU Pelindungan Data Pribadi — JDIH Komdigi</a></li></ul><p>Rujukan untuk informasi; relevansi dan kewajiban spesifik perlu diverifikasi, bukan sertifikasi compliance Ranel.</p></section>
    </>}
    {slug === "pricing-payment" && <section><h2>Ringkasan paket</h2><ul>{offers.map(p => <li key={p.id}>{p.name} — {formatPrice(p.price)} · sekali bayar · pilot/hold</li>)}</ul></section>}
    {slug === "payment-provider" && <p><a href="https://www.duitku.com/">Informasi resmi Duitku</a></p>}
    <nav class="policy-navigation" aria-label="Navigasi kebijakan terkait"><a href="/legal">Legal &amp; Policies</a><a href="/legal/terms">Ketentuan</a><a href="/legal/pricing-payment">Harga &amp; pembayaran</a><a href="/legal/refund-policy">Refund &amp; remedy</a><a href="/legal/privacy">Privasi</a><a href="/legal/license">Lisensi</a><a href="/legal/complaints">Keluhan</a><a href="/contact">Kontak privat</a></nav>
  </article>;
}
